name: mintit

services:
  mint_web:
    container_name: mint_web
    image: git.nexusocean.org/vincent/mint-web:latest
    restart: unless-stopped
    ports:
      - 127.0.0.1:8080:8080
    depends_on:
      mint_api:
        condition: service_started
    networks:
      - mint_net

  mint_api:
    container_name: mint_api
    image: git.nexusocean.org/vincent/mint-api:latest
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      mint_db:
        condition: service_started
    volumes:
      - wallet-data:/app/data/wallet
    networks:
      - mint_net
      - firo_net
      - monero_net

  mint_db:
    container_name: mint_db
    image: mongo:7
    restart: unless-stopped
    expose:
      - 27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB_NAME}
    volumes:
      - ./mongo-data:/data/db
    networks:
      - mint_net

  firod:
    container_name: firod
    image: git.nexusocean.org/containers/firod:latest
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 30s
    expose:
      - 8888
    env_file:
      - .env
    volumes:
      - ./firo-data:/home/firo/.firo
    networks:
      - firo_net

  monerod:
    container_name: monerod
    image: git.nexusocean.org/containers/monerod:v0.18.5.0
    restart: unless-stopped
    stop_signal: SIGTERM
    stop_grace_period: 30s
    volumes:
      - ./monero-data:/home/monero/.bitmonero
    expose:
      - 18081
    command:
      - --rpc-restricted-bind-ip=0.0.0.0
      - --rpc-restricted-bind-port=18089
      - --rpc-bind-ip=0.0.0.0
      - --rpc-bind-port=18081
      - --confirm-external-bind
      - --enable-dns-blocklist
      - --check-updates=disabled
      - --max-log-files=3
      - --max-log-file-size=1048576
      - --no-igd
      - --out-peers=64
      - --limit-rate-down=1048576
      - --public-node
      - --rpc-login=${MONERO_RPC_LOGIN}
    networks:
      - monero_net

volumes:
  wallet-data:

networks:
  mint_net:
    driver: bridge
    name: mint_net
  firo_net:
    driver: bridge
    name: firo_net
  monero_net:
    driver: bridge
    name: monero_net
