name: mintit

services:
  mint_web:
    container_name: mint_web
    image: nexusocean.org/mintit/mint-web:latest
    restart: unless-stopped
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env
    depends_on:
      mint_api:
        condition: service_healthy
    volumes:
      - caddy-data:/data
      - caddy-config:/config
    networks:
      - mint_net

  mint_api:
    container_name: mint_api
    image: nexusocean.org/mintit/mint-api:latest
    restart: unless-stopped
    expose:
      - 3000
    env_file:
      - .env
    depends_on:
      mint_db:
        condition: service_started
    volumes:
      - wallet-data:/app/data/wallet
      - app-data:/app/data/jwt
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/v1/health/ready"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    networks:
      - mint_net
      - firo_net
      - monero_net

  mint_db:
    container_name: mint_db
    image: postgres:18.4
    restart: unless-stopped
    expose:
      - 5432
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - mint_net

volumes:
  wallet-data:
  app-data:
  postgres-data:
  caddy-data:
  caddy-config:

networks:
  mint_net:
    driver: bridge
    name: mint_net
